version: '3.8'

# docker build --tag sae4/front:1.0.0 --target front_nginx --build-arg REACT_APP_API_ENTRYPOINT=http://127.0.0.1:8001/api ..

services:
  react_app:
    image: ${IMAGE_NAME}:${APP_VERSION}
    ports:
      - "8080:80"
    restart: always